apiVersion: v1
kind: Secret
metadata:
  name: leader-access-token
  namespace: leader-ns
  annotations:
    kubernetes.io/service-account.name: antrea-multicluster-member-access-sa
type: kubernetes.io/service-account-token
